---
name: robotcode
description: The Ultimate Robot Framework Toolset
homepage: https://robotcode.io/
licenses:
  - Apache-2.0
languages:
  - Robot Framework
categories:
  - LSP
  - DAP

source:
  id: pkg:pypi/robotcode[all]@1.0.3

bin:
  robotcode: pypi:robotcode
